import {HistoryReport,HistoryDiscussion} from './history-report';
import type { Studies } from './lab';
export function Findings({findings}:{findings:Studies['findings']}) {
 const correct=findings.groups.reduce((sum,g)=>sum+g.controlCorrect,0);
 const choice=findings.current.metrics.find(g=>g.scenario==='all')!;
 const noul=findings.noul.metrics.find(g=>g.scenario==='all')!;
 const total=choice.calls;
 const percent=(n:number,d:number)=>`${(100*n/d).toFixed(1)}%`;
 const primitiveRows=[
  {...choice,label:'Choice · no cutoff',correct:choice.correctBet+choice.correctSkip,expectedProfit:findings.noul.choiceExpectedProfit},
  ...findings.noul.choiceThresholds.filter(row=>row.threshold<0.7).map(row=>({...row,label:`Choice confidence > ${row.threshold.toFixed(1)}`})),
  ...findings.noul.thresholds.filter(row=>row.threshold<0.9).map(row=>({...row,label:`Noul > ${row.threshold.toFixed(1)}`})),
  {...choice,label:'Optimal EV',bets:choice.positive,correctBet:choice.positive,correctSkip:choice.negative,correct:choice.calls,expectedProfit:findings.noul.optimalExpectedProfit},
 ];
 return <><div className="page-heading"><h1>Findings &amp; discussion</h1></div><div className="findings-content"><HistoryReport metrics={findings.current.metrics} interleaved={findings.current.interleaved}/><HistoryDiscussion/>
 <section className="study-feature" aria-labelledby="noul-findings-title"><h2 id="noul-findings-title">Switching to Noul did not solve the EV task.</h2>
 <p>We repeated the same {noul.calls.toLocaleString()} payout and history inputs with Noul, asking whether betting has strictly positive expected net profit. The rule was fixed before collection: <strong>Bet when <code>noul &gt; 0.5</code>; otherwise Skip</strong>, including a tie at 0.5.</p>
 <p>Noul bet on <strong>{percent(noul.bets,noul.calls)}</strong> of offers. It took almost every profitable bet, but correctly skipped only <strong>{percent(noul.correctSkip,noul.negative)}</strong> of negative-EV offers. At this threshold, it performed worse than Choice at distinguishing profitable offers from unprofitable ones.</p>
 <p>Choice bets only when its selected action is Bet and its confidence is strictly above the cutoff. Noul bets when its value is strictly above the cutoff. All other cases, including ties, become Skip; every offer remains in the denominator. Choice confidence measures how concentrated the option distribution is, while Noul judges whether EV is positive. The two scales are not interchangeable.</p>
 <div className="table-scroll control-results primitive-comparison"><table className="study-table-data"><caption>Choice and Noul thresholds · all four histories and three EV ranges · {noul.calls.toLocaleString()} offers per row</caption><thead><tr><th scope="col">Decision rule</th><th scope="col">Bet rate</th><th scope="col">Bet on +EV</th><th scope="col">Skip on −EV</th><th scope="col">Correct overall</th><th scope="col">Total EV</th></tr></thead><tbody>{primitiveRows.map(row=><tr key={row.label}><th scope="row">{row.label}</th><td>{percent(row.bets,row.calls)}</td><td>{percent(row.correctBet,row.positive)}</td><td>{percent(row.correctSkip,row.negative)}</td><td>{percent(row.correct,row.calls)}</td><td>{row.expectedProfit.toLocaleString('en-US',{style:'currency',currency:'USD'})}</td></tr>)}</tbody></table></div>
 <p>Bet on +EV and Skip on −EV each use {noul.positive.toLocaleString()} offers; overall rates use all {noul.calls.toLocaleString()}. Total EV is cumulative expected profit from selected fixed-$100 bets, independent of actual outcomes. Optimal EV is the mathematical benchmark: Bet on positive EV and Skip on negative EV, with no model judgment involved.</p>
 <p>Higher thresholds avoid more negative-EV bets but also miss profitable offers. Only Noul’s 0.5 cutoff was fixed before collection. All other Noul cutoffs and every Choice confidence cutoff are exploratory checks on saved responses, not independently validated rules. The graphs continue to use unfiltered Choice and Noul’s original 0.5 rule.</p>
 <p>The inputs and model version match, but the batches were collected separately and the wording changed from choosing an action to judging a positive-EV proposition. This does not isolate question type alone or establish that every Noul prompt would perform the same way. Its output is a judgment about positive EV, not the chance of winning a roll.</p>
 <p className="study-caveat">Noul source: {findings.noul.provenance}. Choice source: {findings.current.provenance}. Inspect either dataset using the question-type selector on Experiments.</p></section>
 <section className="study-feature"><h2>Supplying the expected value resolved the action task.</h2><p>In a separate supplied-EV control study, Jev chose the EV-optimal action in <strong>{correct.toLocaleString()} of {findings.calls.toLocaleString()} cases ({(correct/findings.calls*100).toFixed(0)}%)</strong>. It bet on positive EV and skipped negative EV across the three tested history conditions.</p><p>This control supplied the calculated expected net profit. It demonstrates using an explicit EV signal, rather than deriving it from payouts. Supplied EV was not tested again in the latest interleaved experiments.</p><div className="table-scroll control-results"><table className="study-table-data"><caption>Separate supplied-EV control · no-history condition not tested</caption><thead><tr><th scope="col">History</th><th scope="col">Correct actions</th><th scope="col">Accuracy</th></tr></thead><tbody>{findings.groups.map(g=><tr key={g.scenario}><th scope="row">{g.scenario==='mixed'?'Mixed outcomes':g.scenario==='wins'?'Six wins':'Six losses'}</th><td>{g.controlCorrect.toLocaleString()} / {g.calls.toLocaleString()}</td><td>{(100*g.controlCorrect/g.calls).toFixed(0)}%</td></tr>)}</tbody></table></div><p className="study-caveat">Control source: {findings.provenance}. This result applies to the tested offers and prompt, not to every numerical or trading decision.</p></section>
 <p className="ledger-footnote">{total.toLocaleString()} decisions across ±1%, ±5% and ±15% ranges. Latest experiment source: {findings.current.provenance}.</p></div></>;
}

